name: Code coverage > 92%

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Update Rust
        run: |
          rustup update stable && rustup default stable
      - name: Aggressive cleanup
        run: |
          # Remove unnecessary tools to increase available disk space
          # Remove Java (JDKs)
          sudo rm -rf /usr/lib/jvm

          # Remove .NET SDKs
          sudo rm -rf /usr/share/dotnet

          # Remove Swift toolchain
          sudo rm -rf /usr/share/swift

          # Remove Android SDKs
          sudo rm -rf /usr/local/lib/android

          # print available disk space
          df -h
      - name: Generate code coverage
        id: llvm_cov_run
        run: |
          # install code coverage tool and measure coverage
          cargo install cargo-llvm-cov
          cargo llvm-cov --all-features --workspace --json --summary-only --output-path ./output.json
          functions=$(jq -r '.data[0].totals.functions.percent | round | tostring' ./output.json)
          lines=$(jq -r '.data[0].totals.lines.percent | round | tostring' ./output.json)
          regions=$(jq -r '.data[0].totals.regions.percent | round | tostring' ./output.json)
          branches=$(jq -r '(.data[0].totals.branches.percent // "NA") | if . == "NA" then "NA" else (. | round | tostring) end' ./output.json)
          echo "function coverage: $functions"
          echo "lines coverage: $lines"
          echo "regions coverage: $regions"
          echo "branches coverage (may not be output if not nightly): $branches"
          if [ "$regions" -le 92 ]; then
            exit 1;
          fi;
          rm ./output.json
