name: Cargo Build & Test (Non-locked packages)

# Although this test is identical to our normal Cargo build & test,
# we have to make this separate as opposed to a matrix job because
# we don't want our badge to be affected.

on:
  push:
    branches: [ "main" ]
  workflow_call:  # Allow calling from release.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup rustup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Delete cargo.lock
        run: rm Cargo.lock
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Cargo clean
        run: cargo clean

  dependency_security:
    name: Dependency security checks (non-locked)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup rustup
        run: rustup update stable && rustup default stable
      - name: Delete cargo.lock
        run: rm Cargo.lock
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Run cargo audit
        run: cargo audit
      - name: Run cargo deny checks
        run: cargo deny check advisories bans sources
